name: Docker Build Deploy

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run shell commands
        run: echo "commit hash is ${{ github.sha }}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}